#!/usr/bin/env bash

#ls -l | awk 'NR >1 {print $8}'
#awk 'BEGIN {print "Hello, World"}'
#awk '{print $0}' dados.txt
#awk '{print $1,$2,$3,$4}' dados.txt
#awk '{print $1" "3}' dados.txt
#awk 'OFS = " -> " {print $1,$3}' dados.txt
#awk 'BEGIN {FS = "-"} $1 ~ "^[0-9]+" {print $1}' resultadosena.txt
#awk 'BEGIN {FS = "-"} $3 ~ "^[0-9]+" {print $1}' resultadosena.txt
awk 'BEGIN {FS = " "} $5 ~ "^[0-9]+" {print $5,$6,$7,$8,$9}' resultadosena.txt
#2502 - 20/07/2022 - 16 20 21 39 44 55 - 0,00 - 0 - 22.920,73 - 103 - 1.157,38 - 2914
#2503 - 23/07/2022 - 03 14 16 38 43 45 - 13.748.083,57 - 1 - 32.808,29 - 91 - 821,15 - 5194
