#!/bin/bash

cNome="Vilmar Catafesta"
cHostname="mazonos"
dialog \
--backtitle "Dialog Form Example" 				\
--title 	"Dialog - Form" 					\
--form 		"\nDialog Sample Label and Values" 	\
25 60 16 \
"Nome do Usuario:" 1 1 "$cNome"     1 25 25 30	\
"Hostname       :" 2 1 "$cHostname" 2 25 25 30	\
"Form Label 3:" 3 1 "Value 3" 3 25 25 30		\
"Form Label 4:" 4 1 "Value 4" 4 25 25 30 2>/tmp/form.$$


shell=""
groups=""
user=""
home=""
exec 3>&1
dialog --separate-widget $'\n' --ok-label "Submit" \
          --backtitle "Linux User Managment" \
          --title "Useradd" \
          --form "Create a new user" \
15 50 0 \
        "Username:" 1 1 "$user"         1 10 10 0 \
        "Shell:"    2 1 "$shell"        2 10 15 0 \
        "Group:"    3 1 "$groups"       3 10 8 0 \
        "HOME:"     4 1 "$home"         4 10 40 0 \
2>&1 1>&3 | {
  read -r user
  read -r shell
  read -r groups
  read -r home

  echo $user
  echo $shell
  echo $groups
  echo $home

  #continue script here
}
exec 3>&-
