#!/usr/bin/env bash

function DrawBox1 {
	string="$*"
	tamanho=${#string}
	tput setaf 4
	printf "\e(0\x6c\e(B"
	for i in $(seq $tamanho); do
		printf "\e(0\x71\e(B"
	done
	printf "\e(0\x6b\e(B\n"
	tput sgr0
	tput setaf 4
	printf "\e(0\x78\e(B"
	tput setaf 1
	tput bold
	echo -n $string
	tput sgr0
	tput setaf 4
	printf "\e(0\x78\e(B\n"
	tput sgr0
	tput setaf 4
	printf "\e(0\x6d\e(B"
	for i in $(seq $tamanho); do
		printf "\e(0\x71\e(B"
	done
	printf "\e(0\x6a\e(B\n"
	tput sgr0
}

function DrawBox {
	string="$*"
	tamanho=${#string}
	tput setaf 4
	printf "\e(0\x6c\e(B"
	printf -v linha "%${tamanho}s" ' '
	printf -v traco "\e(0\x71\e(B"
	echo -n ${linha// /$traco}
	printf "\e(0\x6b\e(B\n"
	tput sgr0
	tput setaf 4
	printf "\e(0\x78\e(B"
	tput setaf 1
	tput bold
	echo -n $string
	tput sgr0
	tput setaf 4
	printf "\e(0\x78\e(B\n"
	tput sgr0
	tput setaf 4
	printf "\e(0\x6d\e(B"
	printf -v linha "%${tamanho}s" ' '
	printf -v traco "\e(0\x71\e(B"
	echo -n ${linha// /$traco}
	printf "\e(0\x6a\e(B\n"
	tput sgr0
}

DrawBox "$@"
