#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# shellcheck shell=bash disable=SC1091,SC2039,SC2166,SC2034
#
#  chili-init-keys - Utilitário para gerenciar e inicializar chaves de assinatura utilizando o pacman
#  Created: 2024/09/23 - 16:19 -04
#  Altered: 2024/09/23 - 16:19 -04
#  Updated: 2024/12/25 - 07:12 -04 - added chili-keyring
#
#  Copyright (c) 2024-2024, Vilmar Catafesta <vcatafesta@gmail.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
#export LANGUAGE=pt_BR
export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=chili-init-keys-manjaro

# Definir a variável de controle para restaurar a formatação original
reset=$(tput sgr0)

# Definir os estilos de texto como variáveis
bold=$(tput bold)
underline=$(tput smul)   # Início do sublinhado
nounderline=$(tput rmul) # Fim do sublinhado
reverse=$(tput rev)      # Inverte as cores de fundo e texto

# Definir as cores ANSI como variáveis
black=$(tput bold)$(tput setaf 0)
red=$(tput bold)$(tput setaf 196)
green=$(tput bold)$(tput setaf 2)
yellow=$(tput bold)$(tput setaf 3)
blue=$(tput setaf 4)
pink=$(tput setaf 5)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)
gray=$(tput setaf 8)
orange=$(tput setaf 202)
purple=$(tput setaf 125)
violet=$(tput setaf 61)
light_red=$(tput setaf 9)
light_green=$(tput setaf 10)
light_yellow=$(tput setaf 11)
light_blue=$(tput setaf 12)
light_magenta=$(tput setaf 13)
light_cyan=$(tput setaf 14)
bright_white=$(tput setaf 15)

#debug
export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset}'
#set -x
#set -e
shopt -s extglob

#system
declare APP="${0##*/}"
declare _VERSION_="1.0.1-2024125"
declare distro
declare DEPENDENCIES=(tput)
#source /usr/share/fetch/core.sh
distro="$(uname -n)"

MostraErro() {
  echo "erro: ${red}$1${reset} => comando: ${cyan}'$2'${reset} => result=${yellow}$3${reset}"
}
#trap 'MostraErro "${APP[$FUNCNAME][$LINENO]}" "${BASH_COMMAND}" "$?"; exit 1' ERR

# /usr/share/pacman/keyrings

sudo rm -rf /etc/pacman.d/gnupg/* 1>/dev/null

# Inicializar e popular o banco de chaves
sudo pacman-key --init 1>/dev/null

# Adicionar e assinar chaves específicas
keys=(
  AECEEE84E52BBFAA9F1C9DF01EA0CEEEB09B44A3  #talesam@gmail.com
  A0D5A8312A83940ED8B04B0F4BAC871802E960F1  #vcatafesta@gmail.com
)

for key in "${keys[@]}"; do
  sudo pacman-key --recv-keys "$key" 1>/dev/null
  sudo pacman-key --lsign-key "$key" 1>/dev/null
done

# Sincronizar pacotes necessários
#sudo pacman -Sy --needed --quiet \
#  archlinux-keyring \
#  manjaro-keyring \
#  biglinux-keyring \
#  community-keyring \
#  chili-keyring \
#  ubuntu-keyring \
#  debian-archive-keyring \
#  alpine-keyring \
#  gnome-keyring \
#  debian-ports-archive-keyring \
#  deepin-polkit-agent-ext-gnomekeyring

sudo pacman-key --init 1>/dev/null
sudo pacman-key --populate 1>/dev/null

# Listar informações das chaves
#sudo pacman-key --list-keys
#sudo pacman-key --list-sigs
#sudo pacman-key --finger
