#!/usr/bin/env bash

#LS_COLORS='di=1;33:hi=1;36' ls -d */ \
#	| grep --color=always '' && ps -eo pid,%mem,cmd --sort=%mem | grep --color=always -E '^[0-9]+|[^ ]*'
#ps -eo pid,%mem,cmd --sort=%mem \
#	| awk 'NR==1 {printf "\033[1;33m%-6s\033[0m \033[1;36m%-6s\033[0m \033[1;35m%-s\033[0m\n", $1, $2, $3} NR>1 {printf "\033[1;33m%-6s\033[0m \033[1;36m%-6s\033[0m \033[1;35m%-s\033[0m\n", $1, $2, $3}'
ps -eo pid,%mem,cmd --sort=%mem | awk '{printf "\033[1;33m%-6s\033[0m \033[1;36m%-6s\033[0m \033[1;35m%-s\033[0m\n", $1, $2, $3}'
#ps -eo pid,%mem,cmd --sort=%mem \
#	| awk 'NR==1 {printf "\033[1;33m%-6s\033[0m \033[1;36m%-6s\033[0m \033[1;35m%-s\033[0m\n", $1, $2, $3} NR>1 {printf "\033[1;33m%-6s\033[0m \033[1;36m%-6s\033[0m \033[1;35m%-s", $1, $2, $3; for (i=4; i<=NF; i++) printf " %s", $i; printf "\033[0m\n"}'
#ps -eo pid,%mem,%cpu,tty,time,cmd --sort=%mem \
#	| awk 'NR==1 {printf "\033[1;33m%-6s\033[0m \033[1;36m%-6s\033[0m \033[1;35m%-s\033[0m\n", $1, $2, $3} NR>1 {printf "\033[1;33m%-6s\033[0m \033[1;36m%-6s\033[0m \033[1;35m%-s", $1, $2, $3; for (i=4; i<=NF; i++) printf " %s", $i; printf "\033[0m\n"}'
