#!/usr/bin/env bash

# This script can be used to create simple chroot environment
# Written by LinuxCareer.com <http://linuxcareer.com/>
# (c) 2013 LinuxCareer under GNU GPL v3.0+

#CHROOT='/var/chroot'
CHROOT="/home/chrootjail"
user='bigbruno'

adir=('proc' 'proc/loadavg' 'dev' 'sys' 'run' 'tmp' 'var' 'usr/bin' 'usr/sbin' 'usr/share' 'usr/lib' 'home')
for dir in "${adir[@]}"; do
	mkdir -p $CHROOT/$dir
done

pushd $CHROOT >/dev/null
chmod 1777 tmp
ln -sf usr/bin bin
ln -sf usr/sbin sbin
ln -sf usr/lib lib
ln -sf usr/lib64 lib64
ln -sf /dev/null dev/null
popd >/dev/null

#retire a permissão de escrita da pasta $CHROOT original
chmod u-w $CHROOT

afilestxt=("/etc/hosts" "/etc/hostname")
set /usr/bin/{bash,sh,id,touch,cat,clear,cp,du,grep,less,ls,mv,mkdir,rmdir,rm,echo,printf,date,awk,uptime,whoami,sed,logname,tput,tree,dircolors,vi,nano,uname,file}
for i in $(ldd $* | grep -v dynamic | cut -d " " -f 3 | sed 's/://' | sort | uniq); do
	cp -f --parents $i $CHROOT
done

## Lista dos arquivos que deseja copiar suas dependências
#afilesbin=("/usr/bin/{bash,sh,id,cat,clear,cp,du,grep,less,ls,mv,mkdir,rmdir,rm,echo,printf,date,awk,uptime,whoami,sed,logname,tput,tree,dircolors,vi,nano,uname,file}")
#for i in "${afiles[@]}"; do
#   # Use eval para expandir a string com chaves para a lista de arquivos
#   eval "filelist=($i)"
#   # Loop para lidar com múltiplos arquivos no caso de usar chaves { } na string
#   for file in "${filelist[@]}"; do
#      # Obtenha as dependências e copie-as para o diretório CHROOT
#      dependencies=$(ldd "$file" | grep -v dynamic | awk '{print $3}' | sed 's/://' | sort | uniq)
#      cp -f --parents $dependencies $CHROOT
#   done
#done

for i in "${afilestxt[@]}"; do
	cp -f --parents $i $CHROOT
done

#para usar com less
cp -r --parents /usr/share/terminfo $CHROOT
cp -f /root/.dircolors $CHROOT/etc/.dircolors

# ARCH amd64
if [ -f /lib64/ld-linux-x86-64.so.2 ]; then
	cp --parents /lib64/ld-linux-x86-64.so.2 /$CHROOT
fi

# ARCH i386
if [ -f /lib/ld-linux.so.2 ]; then
	cp --parents /lib/ld-linux.so.2 /$CHROOT
fi

cat >$CHROOT/bin/chroot-shell <<-EOF
	#!/bin/bash
	#
	# file: /bin/chroot-shell
	#
	/usr/bin/sudo /usr/bin/chroot /home/$USER /bin/su - $USER
EOF
chmod ugo+x $CHROOT/bin/chroot-shell

#echo "root:x:0:root" >$CHROOT/etc/group
#echo "bigbruno:x:1004" >>$CHROOT/etc/group
grep root: /etc/group   >$CHROOT/etc/group
grep $user: /etc/group >>$CHROOT/etc/group

#echo "root:x:0:0:root:/root:/bin/bash" >$CHROOT/etc/passwd
#echo "bigbruno:x:1003:1004::/home/bigbruno:/bin/bash"        >> $CHROOT/etc/passwd
#echo "bigbruno:x:1003:1004::/home/bigbruno:/bin/chroot-shell" >> $CHROOT/etc/passwd
grep root:  /etc/passwd  >$CHROOT/etc/passwd
grep $user: /etc/passwd >>$CHROOT/etc/passwd

sudo groupadd chrootjail
sudo usermod -a -G chrootjail $user

mkdir -p $CHROOT/home/$user
chown $user:$user $CHROOT/home/$user -R

cat >$CHROOT/etc/hostname <<-EOF
$(hostname)
EOF

cat >$CHROOT/etc/hosts <<-EOF
# Static table lookup for hostnames.
# See hosts(5) for details.
127.0.0.1      localhost.localdomain   localhost
::1            localhost.localdomain   localhost
127.0.1.1      chili.localdomain       chili
EOF

cat >$CHROOT/etc/profile <<-EOF
# /etc/profile

# Carregar o arquivo /etc/bashrc se existir
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi
EOF

echo "Chroot jail is ready."
echo "To access it execute: chroot $CHROOT"

#/etc/ssh/sshd_config
#Subsistema SFTP
#	Subsystem sftp internal-sftp

# Configurações para acesso SSH e SFTP do usuário "bigbruno"
#Match User bigbruno
#    ChrootDirectory /home/chrootjail
##	 ChrootDirectory /home/chrootjail/%u
#    AllowTcpForwarding yes
#    X11Forwarding yes
##	  ForceCommand /bin/bash -c "source /etc/bash.bashrc; exec bash"
#	  ForceCommand /bin/bash -c "exec bash"
#    # Aqui você pode configurar outras opções específicas para o acesso SSH e SFTP do usuário "bigbruno"

#Match group chrootjail
#   ChrootDirectory /home/chrootjail

#somente sftp
#Match user bigbruno
#   ChrootDirectory /home/chrootjail/
#	X11Forwarding no
#	AllowTcpForwarding no
#	ForceCommand internal-sftp

