#!/usr/bin/env bash
#shellcheck disable=SC2145,SC2001,SC2188,SC2015,SC2155,SC2317,SC2320,SC2291,SC2034,SC2120,SC2086,SC2319
#shellcheck disable=SC2016,SC2154,SC2207,SC2166,SC2128,SC2059,SC2140,SC2031,SC2030,SC2036,SC2119,SC2027

#  chili-util-selector - Seletor de utilitarios do chili-utils
#  Created: 2022/12/24
#  Altered: 2024/04/12
#  Updated: sáb 15 fev 2025 02:49:14 -04
#
#  Copyright (c) 2022-2024, Vilmar Catafesta <vcatafesta@gmail.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
#export LANGUAGE=pt_BR
export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=chili-util-selector

#debug
export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
#set -x
#set -e
shopt -s extglob

#system
declare APP="${0##*/}"
declare _VERSION_='1.02.17.20250217'
declare APPDESC="Seletor de utilitarios do chili-utils"
declare ccabec="\Z1$APP - \Z2v$_VERSION_ - \Z3$APPDESC - \Z5https://chililinux.com"
declare ctitle="MENU de Utilitários"
declare DEPENDENCIES=(dialog setfont tput)
declare dialogRcFile="$HOME/.dialogrc"
declare sep='\xe2\x94\x82'

cleanup() {
	rm -f "$dialogRcFile"
}
#trap cleanup EXIT

sh_create_dialogrc() {
	cat >"$dialogRcFile" <<EOF
screen_color = (white,black,off)
dialog_color = (white,black,off)
title_color = (cyan,black,on)
border_color = dialog_color
shadow_color = (black,black,on)
button_inactive_color = dialog_color
button_key_inactive_color = dialog_color
button_label_inactive_color = dialog_color
button_active_color = (white,cyan,on)
button_key_active_color = button_active_color
button_label_active_color = (black,cyan,on)
tag_key_selected_color = (white,cyan,on)
item_selected_color = tag_key_selected_color
form_text_color = (BLUE,black,ON)
form_item_readonly_color = (green,black,on)
itemhelp_color = (white,cyan,off)
inputbox_color = dialog_color
inputbox_border_color = dialog_color
searchbox_color = dialog_color
searchbox_title_color = title_color
searchbox_border_color = border_color
position_indicator_color = title_color
menubox_color = dialog_color
menubox_border_color = border_color
item_color = dialog_color
tag_color = title_color
tag_selected_color = button_label_active_color
tag_key_color = button_key_inactive_color
check_color = dialog_color
check_selected_color = button_active_color
uarrow_color = screen_color
darrow_color = screen_color
form_active_text_color = button_active_color
gauge_color = title_color
border2_color = dialog_color
searchbox_border2_color = dialog_color
menubox_border2_color = dialog_color
separate_widget = ''
tab_len = 0
visit_items = off
use_shadow = off
use_colors = on
EOF
	export DIALOGRC="$dialogRcFile"
}

# Testa se o terminal suporta caracteres gráficos estendidos
sh_ascii_lines() {
	#Isso força o dialog a usar caracteres ASCII básicos para as bordas.
	#if [[ "$LANG" =~ 'UTF-8' ]]; then
	if [[ "$(printf '\u250C')" =~ "┌" ]]; then
		export NCURSES_NO_UTF8_ACS=1 # Terminal suporta ACS
	else
		export NCURSES_NO_UTF8_ACS=0 # Terminal NÃO suporta ACS
	fi
}

sh_setEnvironment() {
	[[ ! -e "$dialogRcFile" ]] && sh_create_dialogrc
	sh_ascii_lines
  cLB1=$(gettext "Use as teclas")
  cLB2=$(gettext "PARA CIMA")
  cLB3=$(gettext "e")
  cLB4=$(gettext "PARA BAIXO")
  cLB5=$(gettext "para navegar")
  cLB6=$(gettext "Use")
  cLB7=$(gettext "para alternar entre os botões")
  cLB8=$(gettext "para selecionar")
  cmsg_LABEL="$cLB1${RED} ↑ $cLB2$RESET $cLB3 ${RED}↓ $cLB4$RESET $cLB5\n$cLB6${RED} TAB${RESET} $cLB7${RED} ENTER${RESET} $cLB8"
}

function sh_setvarcolors() {
	if tput setaf 1 &>/dev/null; then
		#tput setaf 127 | cat -v  #capturar saida
		tput sgr0 # reset colors
		bold=$(tput bold)
		reset=$(tput sgr0)
		white="${bold}$(tput setaf 7)"
		black="${bold}$(tput setaf 0)"
		red=$(tput bold)$(tput setaf 196)
		green=$(tput setaf 2)
		yellow=$(tput bold)$(tput setaf 3)
		blue=$(tput setaf 4)
		pink=$(tput setaf 5)
		cyan=$(tput setaf 6)
		orange=$(tput setaf 3)
		purple=$(tput setaf 125)
		violet=$(tput setaf 61)
	else
		bold=''
		reset="\e[0m"
		green="\e[1;32m"
		red="\e[1;31m"
		yellow="\e[1;33m"
		orange="\e[1;33m"
	fi
	# dialog colors
	REVERSE="\Zr"
	UNDERLINE="\Zu"
	BOLD="\Zb"
	RESET="\Zn"
	BLACK="\Z0"
	YELLOW="\Z3"
	WHITE="\Z7"
	BLUE="\Z4"
	CYAN="\Z6"
	RED="\Z1"
	GREEN="\Z2"
	MAGENTA="\Z5"
}

function die() {
	local msg=$1
	shift
	printf "${pink}=> ${red}$msg${reset} ${*}"
	exit 1
}

function msg() {
	local msg=$1
	shift
	printf '%s\n' "${black}$msg${reset}"
	return 0
}

erro() {
	local msg=$1
	shift
	printf '%s\n' "${yellow}=> ${bold}${yellow}$msg${reset}"
	return 1
}

check_deps() {
	local errorFound=false
	declare -a missing

	for d in "${DEPENDENCIES[@]}"; do
		if [[ -z $(command -v "$d") ]]; then
			missing+=("$d")
			errorFound=true
			printf '%s\n' "${red}ERRO${reset}: não encontrei o comando ${orange}'$d'${reset}"
		fi
	done
	if $errorFound; then
		erro "============ IMPOSSÍVEL CONTINUAR ============"
		msg "Esse script precisa dos comandos listados acima"
		msg "Instale-os e/ou verifique se estão no seu \$PATH"
		erro "============ IMPOSSÍVEL CONTINUAR ============"
		die "Abortado..."
	fi
}

sh_chooseutil() {
	local -A aUtils=()
	local -a aUtil_list=()

	aUtils+=(['chili-fr']='Wrapper lite para o qemu')
	aUtils+=(['chili-runimage']='Wrapper lite para o qemu')
	aUtils+=(['chili-dialog-theme-selector']='Seletor de temas para o Dialog')
	aUtils+=(['chili-systemd-services']='Wrapper para o systemctl')
	aUtils+=(['chili-maketar']='Utilitário para criar backup tar de diretórios')
	aUtils+=(['chili-parted']='Wrapper parted para particionamento de disco')
	aUtils+=(['chili-xrandr']='Wrapper config resolution using xrandr, umc e cvt')
	aUtils+=(['chili-locale_config']='Wraper para o localectl para ajustar o idioma')
	aUtils+=(['chili-glibc-version']='Mostra a versão da libc')
	aUtils+=(['chili-chroot']='chroot util compatible with all likeunix')
	aUtils+=(['chili-wifi-config']='Wrapper configuração wifi para o NetworkManager')
	aUtils+=(['chili-clonedisk']='Utilitário para clonar disco')
	aUtils+=(['chili-efivar']='Listar variáveis uefi')
	aUtils+=(['chili-make-pacman-conf']='Utility to add repositories to pacman.conf and manage keys')
	aUtils+=(['chili-init-keys']='Utility for managing keys using pacman-key')
	aUtils+=(['chili-syncdatetime']='Utilitario para sincronizar data e hora com servidor NTP')

	for key in "${!aUtils[@]}"; do
		aUtil_list+=("$key" "${aUtils[$key]}")
    if ((nlen < ${#key})); then
      nlen=${#key}
    fi
	done

  ((nlen += 5))
	util_choice=$(dialog \
		--default-item "$util_choice" \
		--colors \
		--clear \
		--title "$ctitle" \
		--backtitle "$ccabec" \
		--ok-label "Executar APP" \
		--cancel-label "Sair" \
		--menu "$cmsg_LABEL\n\n\
$(printf "%${nlen}s$sep%-30s %${nlen}s" "NOME APP" "DESCRIÇÃO APP")" \
		0 0 20 "${aUtil_list[@]}" 2>&1 >/dev/tty)

	if [ -n "$util_choice" ]; then
		clear
		exec sudo "$util_choice"
	else
		exit 0
	fi
}

sh_setvarcolors
sh_setEnvironment
check_deps
sh_chooseutil "$@"
