#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# shellcheck shell=bash disable=SC1091,SC2039,SC2166
#
#  chili-install_package_without_exec_hook
#  Created: 2025/03/10 - 07:53
#  Altered: 2025/03/10 - 07:53
#
#  Copyright (c) 2025-2025, Vilmar Catafesta <vcatafesta@gmail.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
#export LANGUAGE=pt_BR
export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=chili-install_package_without_exec_hook

# Definir a variável de controle para restaurar a formatação original
reset=$(tput sgr0)

# Definir os estilos de texto como variáveis
bold=$(tput bold)
underline=$(tput smul)   # Início do sublinhado
nounderline=$(tput rmul) # Fim do sublinhado
reverse=$(tput rev)      # Inverte as cores de fundo e texto

# Definir as cores ANSI como variáveis
black=$(tput bold)$(tput setaf 0)
red=$(tput bold)$(tput setaf 196)
green=$(tput bold)$(tput setaf 2)
yellow=$(tput bold)$(tput setaf 3)
blue=$(tput setaf 4)
pink=$(tput setaf 5)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)
gray=$(tput setaf 8)
orange=$(tput setaf 202)
purple=$(tput setaf 125)
violet=$(tput setaf 61)
light_red=$(tput setaf 9)
light_green=$(tput setaf 10)
light_yellow=$(tput setaf 11)
light_blue=$(tput setaf 12)
light_magenta=$(tput setaf 13)
light_cyan=$(tput setaf 14)
bright_white=$(tput setaf 15)

#debug
export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset}'
#set -x
#set -e
shopt -s extglob

#system
declare APP="${0##*/}"
declare _VERSION_="1.0.0-20250310"
declare distro="$(uname -n)"
declare DEPENDENCIES=(tput)
source /usr/share/fetch/core.sh

MostraErro() {
  echo "erro: ${red}$1${reset} => comando: ${cyan}'$2'${reset} => result=${yellow}$3${reset}"
}
trap 'MostraErro "$APP[$FUNCNAME][$LINENO]" "$BASH_COMMAND" "$?"; exit 1' ERR
set -e

# Mensagem inicial em azul e em negrito
echo -e "${blue}${bold}Iniciando o script de instalação...${reset}"

# Baixar o pacote sem instalá-lo
PACKAGE_NAME="$1"
if [ -z "$PACKAGE_NAME" ]; then
    echo -e "${red}Erro: O nome do pacote deve ser passado como parâmetro.${reset}"
    echo -e "${yellow}Uso: $0 <nome_do_pacote>${reset}"
    exit 1
fi

echo -e "${cyan}Baixando o pacote ${green}$PACKAGE_NAME${cyan}...${reset}"
sudo pacman -Sw --noconfirm "$PACKAGE_NAME" 1>/dev/null

# Seleciona o pacote mais recente no cache
PACKAGE=$(ls -1t /var/cache/pacman/pkg/"$PACKAGE_NAME"-*.pkg.tar.* | head -n 1)
if [ -z "$PACKAGE" ]; then
    echo -e "${red}Erro: pacote $PACKAGE_NAME não encontrado no cache.${reset}"
    exit 1
fi
echo -e "${green}Pacote encontrado: $PACKAGE${reset}"

# Cria um diretório temporário para extrair o pacote
TMP_DIR=$(mktemp -d /tmp/"$PACKAGE_NAME"-extract-XXXXXX)
echo -e "${cyan}Extraindo o pacote para ${yellow}$TMP_DIR${reset}..."
bsdtar -xf "$PACKAGE" -C "$TMP_DIR"

# Copia os arquivos extraídos para o sistema, excluindo metadados desnecessários
echo -e "${magenta}Copiando os arquivos para o sistema, ignorando arquivos desnecessários...${reset}"
sudo rsync -av --exclude='.BUILDINFO' --exclude='.INSTALL' --exclude='.MTREE' --exclude='.PKGINFO' "$TMP_DIR"/ / 1>/dev/null

# Remove o diretório temporário
echo -e "${violet}Limpando diretório temporário...${reset}"
rm -rf "$TMP_DIR"

echo -e "${green}${bold}Instalação manual do pacote $PACKAGE_NAME concluída!${reset}"
