#!/usr/bin/env bash

clear
for ((Cor=0; Cor <= 7; Cor++)) {
	for Modo in sgr0 bold; {
		tput $Modo
		tput setaf $Cor
		printf -v Linha 	"%-$(tput cols)s" 					\
								"Cor[$Cor]$([ $Modo = sgr0 ]	&&	\
								echo "Normal"	 					||	\
								echo "++Bold"):"
		sed "s/ /▒/g" <<< "$Linha"
	}
	tput sgr0
}

echo "$(tput setaf 31) MENSAGEM"



