#!/usr/bin/env bash

clear
for ((Cor = 0; Cor <= 7; Cor++)); do
	for Modo in sgr0 bold; do
		tput $Modo
		tput setaf $Cor
		printf -v Linha "%-$(tput cols)s" \
			"Cor[$Cor]$([ $Modo = sgr0 ] &&
				echo "Normal" ||
				echo "++Bold"):"
		sed "s/ /▒/g" <<<"$Linha"
	done
	tput sgr0
done

echo "$(tput setaf 31) MENSAGEM"
