#!/usr/bin/env bash

# Função para definir as cores usando tput
definir_cores() {
	cor_vermelho=$(tput setaf 1)
	cor_verde=$(tput setaf 2)
	cor_magenta=$(tput setaf 5)
	cor_reset=$(tput sgr0)
}

# Função para mostrar o conteúdo do cabeçalho de arquivos binários
mostrar_conteudo_cabecalho() {
	arquivo="$1"
	tipo_cabecalho="$2"
	cabecalho=$(xxd -l 16 -p "$arquivo")
	echo "Cabeçalho do arquivo '$arquivo' (primeiros 16 bytes em hexadecimal):"
	echo "$cabecalho"
}

# Verifica se o número de argumentos é válido
if [ "$#" -eq 0 ]; then
	echo "Uso: $0 [opções] [diretório] string"
	echo "Opções:"
	echo "  -c, --conteudo TIPO    Mostrar o conteúdo do cabeçalho de um arquivo binário com o TIPO especificado"
	exit 1
fi

# Verifica se a opção "-c" ou "--conteudo" foi especificada
if [[ "$1" == "-c" || "$1" == "--conteudo" ]]; then
	# Verifica se o número de argumentos é válido para a opção "-c" ou "--conteudo"
	if [ "$#" -ne 3 ]; then
		echo "Uso: $0 --conteudo TIPO arquivo"
		exit 1
	fi

	tipo_cabecalho="$2"
	arquivo="$3"

	# Verifica se o arquivo existe
	if [ ! -f "$arquivo" ]; then
		echo "O arquivo '$arquivo' não existe."
		exit 1
	fi

	# Mostrar o conteúdo do cabeçalho do arquivo binário
	mostrar_conteudo_cabecalho "$arquivo" "$tipo_cabecalho"

	exit 0
fi

# Verifica se o primeiro argumento é um diretório válido
if [ -d "$1" ]; then
	diretorio="$1"
	shift 1
else
	diretorio="$PWD"
fi

# Verifica se o diretório existe
if [ ! -d "$diretorio" ]; then
	echo "O diretório '$diretorio' não existe."
	exit 1
fi

# Verifica se a string de pesquisa foi fornecida
if [ "$#" -ne 1 ]; then
	echo "Uso: $0 [opções] [diretório] string"
	echo "Opções:"
	echo "  -c, --conteudo TIPO    Mostrar o conteúdo do cabeçalho de um arquivo binário com o TIPO especificado"
	exit 1
fi

string="$1"

# Definir as cores
definir_cores

# Utiliza o comando 'find' para procurar arquivos com o conteúdo fornecido
# A opção '-type f' indica que estamos procurando apenas por arquivos, não diretórios
# A opção '-exec' executa o comando 'grep' para verificar o conteúdo do arquivo
# '{}' é substituído pelo nome do arquivo encontrado pelo 'find'
# '+' indica que o comando '-exec' será executado com vários argumentos (todos os arquivos encontrados)
# O comando 'grep' utiliza a opção '-H' para mostrar o caminho completo do arquivo
# A opção '-n' do 'grep' mostra o número da linha onde a string é encontrada
grep_output=$(find "$diretorio" -type f -exec grep -Hn "$string" {} + 2>/dev/null)

# Exibe o resultado na tela com cores
if [ -n "$grep_output" ]; then
	echo "${cor_verde}Arquivos que contêm a string '$string':${cor_reset}"
	echo "$grep_output" | sed -E "s/(${string}.*):/${cor_magenta}\1${cor_reset}/" | sed "s/:\([0-9]\+\):/:${cor_verde}\1${cor_reset}/"
else
	echo "${cor_vermelho}Nenhum arquivo encontrado com a string '$string' em '$diretorio'.${cor_reset}"
fi
