#!/bin/bash

function fontedialog(){
while true
do
	dir="/usr/share/consolefonts/"
	fontes=($(ls $dir))
	sd=$(dialog --clear 														\
				--backtitle	 	"$dir"						 					\
				--cancel-label 	"Cancelar"										\
				--menu 			"Escolha a fonte com enter:" 0 50 15 "${fontes[@]}" 2>&1 >/dev/tty 	)

	exit_status=$?
	case $exit_status in
		1)
			exit 1
			;;
		255)
			exit 0
			;;
	esac
	if [ $sd <> 0 ]; then
		setfont $sd
	fi
done
}
clear
fontedialog
