#!/usr/bin/env bash

file='/tmp/packages-installed-split.csv'
:<<'comment'
mapfile -t public_pkg_main < "$file"
main7=${public_pkg_main[@]%,*}; a7=${public_pkg_main[@]##*,}
main6=${main7[@]%,*}; a6=${main7[@]##*,}
main5=${main6[@]%,*}; a5=${main6[@]##*,}
main4=${main5[@]%,*}; a4=${main5[@]##*,}
main3=${main4[@]%,*}; a3=${main4[@]##*,}
main2=${main3[@]%,*}; a2=${main3[@]##*,}
main1=${main2[@]%,*}; a1=${main2[@]##*,}

echo ${main[@]}
echo 1 - ${a1[@]}
echo 2 - ${a2[@]}
echo 3 - ${a3[@]}
echo 4 - ${a4[@]}
echo 5 - ${a5[@]}
echo 6 - ${a6[@]}
echo 7 - ${a7[@]}
exit

	public_pkg_base=($(awk -F$SEP '{ print $1 }' $file_list_packages))
	public_pkg_version=($(awk -F$SEP '{ print $2 }' $file_list_packages))
	public_pkg_build=($(awk -F$SEP '{ print $3 }' $file_list_packages))
   public_pkg_fullname=($(awk -F$SEP '{ print $4 }' $file_list_packages))
#  public_pkg_dirfullname=($(awk -F$SEP '{ print $5 }' $file_list_packages))
#  public_pkg_base_version=($(awk -F$SEP '{ print $6 }' $file_list_packages))
#  public_pkg_size=($(awk -F$SEP '{ print $7 }' $file_list_packages))
   public_pkg_site=($(awk -F$SEP '{ print $8 }' $file_list_packages))
comment

func()
{
	indice=$1
	linha=$2
#	final+=(${linha%%,*})
	final+=($linha)
}

#mapfile -d, -t -c1 -C 'func' campo < "$file"
#echo ${campo[@]}
#echo ${campo2[@]}
#echo ${final[@]}

#foo(){
#	echo "[$2]"
#	mapfile -t a <<< "$2"
#}
#mapfile -t -d, -c1 -C 'foo' < packages-installed-split.csv
#echo ${a[@]}

showRecord() {
    printf 'key[%d] = %d, %d\n' "$1" "${vals[@]:keys[$1]*2:2}"
}

parseRecords() {
    trap 'unset -f _f' RETURN
    _f() {
        local x
        IFS=: read -r _ x
        ((keys[x]=n++))
    }
    local n

    _f
    mapfile -tc2 -C _f "$1"
    eval "$1"'=("${'"$1"'[@]##*:}")' # Return the array with some modification
}

main() {
    local -a keys vals
    parseRecords vals
    showRecord "$1"
}

main "$1" <<-"EOF"
fabric.domain:123
routex:1
routey:2
fabric.domain:321
routex:6
routey:4
EOF
