#!/usr/bin/env bash

source /chili/core.sh

sh_confadduser() {
	cfullname="Vilmar Catafesta"
	cuser="vcatafesta"
	cpass=""
	cpassroot=""
	chostname="chili"
	ccreatenewuser="Cria usuario"

	exec 3>&1
	usertext=$(dialog \
		--backtitle "$cmsgusermanager" \
		--insecure "$@" \
		--mixedform "$ccreatenewuser" \
		12 50 0 \
		"Nome Completo : " 1 1 "$cfullname" 1 17 40 0 0 \
		"Username      : " 2 1 "$cuser" 2 17 20 0 0 \
		"Password user : " 3 1 "$cpass" 3 17 20 0 1 \
		"Password root : " 4 1 "$cpassroot" 4 17 20 0 1 \
		"Hostname      : " 5 1 "$chostname" 5 17 20 0 0 \
		2>&1 1>&3)
	exit_status=$?

	#       	echo "$usertext"
	#       	usertext=$(sed 's/^/\n/' <<< "$usertext")
	#       	usertext="${usertext//^/\n/}"
	#       	usertext="${usertext// /\n/}"

	case $exit_status in
	0)
		#					modo 1
		#					aUser=()
		#		        	while read -r line; do
		#		         	aUser+=("$line")
		#		        	done <<< "$(printf '%s\n' "${usertext[@]}")"

		#					modo 2
		#					mapfile -t <<< "$usertext" aUser
		#					printf '%s\n' "${aUser[@]}"
		#					exit

		#					modo 3
		#					while read line; do
		# 						aUset+=("$line")
		#					done <<< "${usertext// /\n}"

		cfullname="${aUser[0]}"
		cuser="${aUser[1]}"
		cpass="${aUser[2]}"
		cpassroot="${aUser[3]}"
		chostname="${aUser[4]}"

		echo "1 $cfullname"
		echo "2 $cuser"
		echo "3 $cpass"
		echo "4 $cpassroot"
		echo "5 $chostname"

		[[ "$cuser" == "root" ]] && {
			info "erro"
			sh_confadduser
		}
		;;
	1) exit ;;
	esac
	exec 3>&-
}

sh_confadduser
