#!/usr/bin/env bash

tput sgr0 # reset colors
bold=$(tput bold)
reset=$(tput sgr0)
red=$(tput setaf 124)
yellow=$(tput setaf 136)
pink=$(tput setaf 129)

export PS4=$'${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
set -x
set -e

sh_romeu() {
	if efivar --list 2>&1; then
		return 0
	fi | tee -i -a "filelog.log" >/dev/tty8
	return 1
}

sh_bootefi() {
	efivar --list 2>&1 | tee -i -a 'filelog.log' >/dev/tty8
	RetCode=("${PIPESTATUS[@]}")
	echo ${PIPESTATUS[0]}, ${PIPESTATUS[1]} #efivar,tee
	grep alguma.máquina.exemplo.com /etc/hosts 2>&1
	echo ${PIPESTATUS[0]}, ${PIPESTATUS[1]} #grep,null
	#	return ${PIPESTATUS[0]}											#echo
	return ${RetCode[0]} #efivar

}

if sh_bootefi; then
	echo 'ok'
	exit 0
fi
echo 'deu ruim'
exit 1

set -o pipefail
if false | false | true; then echo SUCCESS; else echo FAIL; fi
if true | false | true; then echo SUCCESS; else echo FAIL; fi
if false | true | true; then echo SUCCESS; else echo FAIL; fi
if true | true | false; then echo SUCCESS; else echo FAIL; fi
if true | true | true; then echo SUCCESS; else echo FAIL; fi
