#!/usr/bin/env bash

ip=192.168.1.15
#regex='([0-9]{1,3}\.)(?1)(?1)[0-9]{1,3}'
regex='(([0-9]+\.)([0-9]+\.)[0-9]+\.[0-9]+)'
regex='([0-9]+\.)([0-9]+\.)([0-9]+\.)([0-9]+)'
echo $ip
echo $regex
[[ "$ip" =~ $regex ]]
echo $?
echo ${BASH_REMATCH[@]}
echo ${BASH_REMATCH[1]}
echo ${BASH_REMATCH[2]}
echo ${BASH_REMATCH[3]}
echo ${BASH_REMATCH[4]}

