#!/usr/bin/env bash

#wget https://www.gnu.org/software/bash/manual/bash.html -qO - | sed -En 's|^.*toc-.*href="\K([^"]+).*>(.*)<\/a>.*|\1 \2|p'	#VC
#wget https://www.gnu.org/software/bash/manual/bash.html -qO - | sed -En 's|^.*toc-.*href="([^"]+).*>(.*)<\/a>.*|\2 \1|p'	#VC
#wget https://www.gnu.org/software/bash/manual/bash.html -qO - | sed -En 's|.*toc-.*href="([^"]+)">(.*)</a>.*|\2 \1|p' 		#BLAU

#str=$'boa noite tarde\boa tarde noite\nboa noite noite\nboa tarde tarde'
#grep -E 'boa (tarde|noite) \1' <<< $str

wget https://www.gnu.org/software/bash/manual/bash.html -qO - > file.txt
pat='^.*toc-.*href="([^"]+).*>(.*)<\/a>.*'
while IFS= read -r line; do
   [[ $line =~ $pat ]] &&
   echo "${BASH_REMATCH[2]} ${BASH_REMATCH[1]}"
done <file.txt
