#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# shellcheck shell=bash disable=SC1091,SC2039,SC2166
#
#  remove_bridge_virbr
#  Created: 2025/01/20 - 22:22
#  Altered: 2025/01/20 - 22:22
#
#  Copyright (c) 2025-2025, Vilmar Catafesta <vcatafesta@gmail.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
#export LANGUAGE=pt_BR
export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=remove_bridge_virbr

# Definir a variável de controle para restaurar a formatação original
reset=$(tput sgr0)

# Definir os estilos de texto como variáveis
bold=$(tput bold)
underline=$(tput smul)   # Início do sublinhado
nounderline=$(tput rmul) # Fim do sublinhado
reverse=$(tput rev)      # Inverte as cores de fundo e texto

# Definir as cores ANSI como variáveis
black=$(tput bold)$(tput setaf 0)
red=$(tput bold)$(tput setaf 196)
green=$(tput bold)$(tput setaf 2)
yellow=$(tput bold)$(tput setaf 3)
blue=$(tput setaf 4)
pink=$(tput setaf 5)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)
gray=$(tput setaf 8)
orange=$(tput setaf 202)
purple=$(tput setaf 125)
violet=$(tput setaf 61)
light_red=$(tput setaf 9)
light_green=$(tput setaf 10)
light_yellow=$(tput setaf 11)
light_blue=$(tput setaf 12)
light_magenta=$(tput setaf 13)
light_cyan=$(tput setaf 14)
bright_white=$(tput setaf 15)

#debug
export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset}'
#set -x
#set -e
shopt -s extglob

#system
declare APP="${0##*/}"
declare _VERSION_="1.0.0-20250120"
declare distro="$(uname -n)"
declare DEPENDENCIES=(tput)
source /usr/share/fetch/core.sh

# Função para exibir mensagens informativas
msg_info() {
  echo -e "${yellow}[INFO] ${cyan}$1${reset}"
}

# Função para exibir mensagens informativas
msg_err() {
  echo -e "${red}[ERRO] ${cyan}$1${reset}"
}

remove_bridge_and_tap() {
  local bridge_name=$1
  local tap_name="tap$(echo "$bridge_name" | sed 's/[^0-9]*//g')" # Ajuste para pegar o número correto do tap

  # Remover a bridge
  msg_info "Removendo a bridge $bridge_name..."
  sudo ip link set "$bridge_name" down 1>/dev/null
  sudo brctl delbr "$bridge_name" 1>/dev/null

  # Remover a interface TAP associada
  if ip link show "$tap_name" &>/dev/null; then
    msg_info "Removendo a interface TAP $tap_name..."
    sudo ip link set "$tap_name" down 1>/dev/null
    sudo ip tuntap del dev "$tap_name" mode tap 1>/dev/null
  else
    msg_err "A interface TAP $tap_name não existe."
  fi

  # Remover a rede do libvirt
  msg_info "Removendo a rede do libvirt..."
  sudo virsh net-destroy "$bridge_name" 1>/dev/null
  sudo virsh net-autostart --disable "$bridge_name" 1>/dev/null
  sudo virsh net-undefine "$bridge_name" 1>/dev/null
  sudo ip link delete "$bridge_name"
  sudo systemctl restart libvirtd

  # Remover a configuração da rede do libvirt, caso fique residuos
  local network_config="/etc/libvirt/qemu/networks/${bridge_name}.xml"
  local network_config_autostart="/etc/libvirt/qemu/networks/autostart/${bridge_name}.xml"
  msg_info "Removendo o arquivo de configuração da rede $bridge_name..."
  sudo rm -fv "$network_config" 1>/dev/null
  sudo rm -fv "$network_config_autostart" 1>/dev/null

  msg_info "Bridge $bridge_name e TAP $tap_name removidos com sucesso."
}

# Verifica se o nome da bridge foi passado como parâmetro
if [ -z "$1" ]; then
  msg_info "Erro: Nenhuma interface foi especificada."
  exit 1
fi

# Chama a função para remover a bridge e a interface associada
remove_bridge_and_tap "$1"

