#!/usr/bin/env bash
# shellcheck shell=bash disable=SC1091,SC2039,SC2166

#  Copyright (c) 2022-2024, Vilmar Catafesta <vcatafesta@gmail.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################

# Percorre todos os arquivos no diretório atual
for file in *; do
    # Verifica se o nome do arquivo contém espaços e parênteses
    if [[ "$file" == *" "* && "$file" == *"("* && "$file" == *")"* ]]; then
        # Remove os espaços substituindo por underscores
        new_name=$(echo "$file" | tr ' ' '_')

        # Remove os parênteses
        new_name=${new_name//'('/}
        new_name=${new_name//')'/}

        # Renomeia o arquivo
        mv -v "$file" "$new_name"
    elif [[ "$file" == *"("* && "$file" == *")"* ]]; then
        # Remove os parênteses
        new_name=${file//'('/}
        new_name=${new_name//')'/}

        # Renomeia o arquivo
        mv -v "$file" "$new_name"
    fi
done
