#!/usr/bin/env bash

sh_debug()
{
   # debug
   #declare -A cores=( [bla]=0 [red]=1 [gre]=2 [yel]=3 [blu]=4 [mag]=5 [cya]=6 [whi]=7 )
   #fg=${cores[bla]}
   #bg=${cores[red]}
   #export PS4=$'+\t${0##*/}[$LINENO] '
   #set -x
   #set -Eeuo pipefail
   #trap 'echo "${BASH_SOURCE}:${LINENO}:${FUNCNAME:-}"' ERR

   sh_setvarcolors
   export PS4=$'${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
   #set -x
   #set -e
   # end debug

   #set -a                 # Enable allexport using single letter syntax
   #set -o allexport       # Enable using full option name syntax
   #set +a                 # Disable allexport using single letter syntax
   #set +o allexport       # Enable using full option name syntax
}


