#!/usr/bin/env bash

# Função para exibir mensagem de ajuda
help() {
   echo "Uso: $0 <porta local> <porta remota>"
   echo "Exemplo: $0 1234 5678"
   exit 1
}

# Verifica se o número de argumentos é válido
if [[ $# -ne 2 ]]; then
   help
fi

# Verifica se as portas são válidas
if ! [[ $1 =~ ^[0-9]+$ ]] || ! [[ $2 =~ ^[0-9]+$ ]]; then
   help
fi

# Define as portas e o modo verboso do Netcat
sport=$1
dport=$2
nc_options="-v"

# Função para iniciar o servidor
init-server() {
   while :; do
      while read -r line; do
         echo "$line"
      done < <(nc $nc_options -l -p "$sport")
   done
}

# Função para iniciar o cliente
init-client() {
   while :; do
      read -r msg
      [[ -n $msg ]] && echo "$msg" > /dev/tcp/localhost/$dport
   done
}

# Exibe a mensagem de inicialização e inicia as funções do servidor e do cliente
echo "Escutando na porta $sport"
init-server &
init-client
