#!/usr/bin/env bash

host="localhost"
port="3333"

# escuta a porta 3333 e lê as mensagens recebidas
while true; do
    if read -r msg < <(nc -l -p "$port"); then
        # exibe a mensagem na tela do X Window System
        xmessage "$msg"
    fi
done
