#!/bin/bash
# concatenates selected files in one file and moves the old ones to Trash
# to be used with files generated by 'split' GNU/Linux utility
# Marius Andreiana <mandreiana AT yahoo.com>
# Licence: GPL
#
# TODO
# how to do it without temp file 'nautilus_script_files' ?
# force nautilus refresh after exec
# 
concat_file_name=$( echo $1 | sed s/'..$'/""/g )
#cd $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
for arg
do
    echo "$arg" >> nautilus_script_files
done

cat $( cat nautilus_script_files | sort ) > $concat_file_name
rm -f nautilus_script_files

for arg
do
    mv "$arg" ~/.Trash
done
