package main

import (
	"encoding/json"
	"fmt"
)

type AutoGenerated struct {
	Nome          string  `json:"Nome"`
	Sobrenome     string  `json:"Sobrenome"`
	Idade         int     `json:"Idade"`
	Profissao     string  `json:"Profissao"`
	Contabancaria float64 `json:"Contabancaria"`
}

type pessoa struct {
	Nome          string
	Sobrenome     string
	Idade         int
	Profissao     string
	Contabancaria float64
}

func main() {
	testMarshal()
	testUnMarshal()
}

func testMarshal() {
	jamesbond := pessoa{
		Nome:          "James",
		Sobrenome:     "Bond",
		Idade:         40,
		Profissao:     "Agente Secreto",
		Contabancaria: 1000000.50,
	}

	darthvader := pessoa{"Anakin", "Skywalker", 50, "Vilão Intergaláctio", 50.83}

	j, err := json.Marshal(jamesbond)
	if err != nil {
		fmt.Println(err)
	}
	d, err := json.Marshal(darthvader)
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(string(j))
	fmt.Println(string(d))
}

func testUnMarshal() {

	sb := []byte(`{"Nome":"James","Sobrenome":"Bond","Idade":40,"Profissao":"Agente Secreto","Contabancaria":10.5}`)
	var jamesbond AutoGenerated
	err := json.Unmarshal(sb, &jamesbond)
	if err != nil {
		fmt.Println("Error:", err)
	}
	fmt.Println(jamesbond)
	fmt.Println(jamesbond.Nome)
	fmt.Println(jamesbond.Profissao)
}
