#!/usr/bin/env bash
# shellcheck shell=bash disable=SC1091,SC2039,SC2166

[[ $# -lt 1 ]] && { echo "Uso: $0 <file.go>"; exit 1; }
#go build -tags netgo -ldflags '-s -w -extldflags "-static"' "$@"
if go build -gcflags "-trimpath" -ldflags "-s -w" "$1.go"; then
	exec $1
fi


