.PHONY: clean All

All:
	@echo "----------Building project:[ ponteiro - Debug ]----------"
	@"$(MAKE)" -f  "ponteiro.mk"
clean:
	@echo "----------Cleaning project:[ ponteiro - Debug ]----------"
	@"$(MAKE)" -f  "ponteiro.mk" clean
